### PR TITLE
Building own Face recognition 

### PR DESCRIPTION
**Pull request by bharath-acchu**
issue #185

### CODE REVIEW

**Comment by Jayshah6699** [comment]
close all pull requests delete all of the stuff you have added clone the latest version of repo and then add everything one by one by making pull request

**Comment by bharath-acchu** [comment]
Should I close only recent 3 prs and Add them?

**Comment by Jayshah6699** [comment]
yes

**Comment by Jayshah6699** [comment]
@bharath-acchu ping me on discord

**Pull request closed without merging**
