### PR TITLE
Updated readme.md

### PR DESCRIPTION
**Pull request by tharunc**
Hello there,
      1) I have included your First significant Example, with labels.
      2) I have included CODE OF CONDUCT
      3) I have assigned Contributors that can link to to your profile.
      4) I have edited grammatical errors.
      5) I have added suitable description.

If there is any further discrepancy, kindly let me know. 

                                                                           THANK YOU

### CODE REVIEW

**Comment by Jayshah6699** [comment]
remove my orignal image go for my github profile image.

**Comment by Jayshah6699** [comment]
I will suggest making a GitHub action that directly adds the contributors whenever I merge any pull request and example of every project isn't necessary on the home page as every project will have it's own markdown file explaining the project itself

**Comment by tharunc** [comment]
I have removed your Original Picture, with your Github's Profile image. I have also removed the examples.
Please merge my Request.
THANK YOU

**Comment by Jayshah6699** [comment]
@all-contributors please add @tharunc for Code and Documentation

**Pull request merged**
