### PR TITLE
Added all the files related to predicting employee attrition project

### PR DESCRIPTION
**Pull request by manvi0308**
### Project -> Predicting Employee Attrition

Aim of Project -> As the COVID-19 keeps unleashing its havoc, the world continues to get pushed into the crisis of the great economic recession, more and more companies start to cut down their underperforming employees. Companies firing hundreds and thousands of Employees is a typical headline today. Cutting down employees or reducing an employee salary is a tough decision to take. It needs to be taken with utmost care as imprecision in the identification of employees whose performance is attriting may lead to sabotaging of both employees' career and the company's reputation in the market.

_Description of files added_

1. training_data.csv -> training data in csv format
2. testing_data.csv -> testing data in csv format
3. hr-attrition-prediction.ipynb -> Jupyter notebook of project
4. data description.txt -> A .txt file that gives full description of the project as well as the dataset

### CODE REVIEW

**Comment by manvi0308** [comment]
@Jayshah6699 I have added all the datasets, and project notebook

**Comment by Jayshah6699** [comment]
mention the issue number here @manvi0308

**Comment by manvi0308** [comment]
Issue number #29

**Comment by manvi0308** [comment]
Kindly merge this to your repo

**Comment by Jayshah6699** [comment]
this is pull request link not the issue link @manvi0308

**Comment by Jayshah6699** [comment]
#22

**Comment by Jayshah6699** [comment]
@manvi0308 kindly reopen the issue and pullrequest and mention correct issue number in the hash tag

**Comment by Jayshah6699** [comment]
@all-contributors please add @manvi0308 for Code and Documentation

**Pull request merged**
