### PR TITLE
Music Genre Classification

### PR DESCRIPTION
**Pull request by bharath-acchu**

### CODE REVIEW

**Comment by Jayshah6699** [comment]
mention issue number

**Comment by bharath-acchu** [comment]
issue no #174

**Comment by Jayshah6699** [comment]
can you add some sort of output where you enter any mp3 or any music file and your model predicts the output?

**Comment by bharath-acchu** [comment]
@Jayshah6699  the output is mentioned at the end of README file , kindly look into it  link to readme is [here](https://github.com/bharath-acchu/datascience-mashup/blob/music/Music%20genre%20classification/README.md)

**Comment by Jayshah6699** [comment]
I know that... I am suggesting an interface with a simple file selection box where the user selects music file and it gives an output.
I am suggesting an interface instead of the command line.

**Comment by Jayshah6699** [comment]
interface as in the website.

**Pull request merged**
