### PR TITLE
Loan Prediction

### PR DESCRIPTION
**Pull request by Bhagyashri2000**
Loan prediction model using Logistic Regression and deployment using Flask and Heroku cloud

### CODE REVIEW

**Comment by Jayshah6699** [comment]
Get some bigger dataset and apply your model on that for getting better accuracy.

**Comment by Bhagyashri2000** [comment]
Okay

**Comment by Bhagyashri2000** [comment]
I could not find any bigger dataset. This dataset has been used everywhere

**Comment by Jayshah6699** [comment]
mention issue number here

**Comment by Jayshah6699** [comment]
#23

**Pull request merged**
