### PR TITLE
Used car price estimation: 96% accuracy #175

### PR DESCRIPTION
**Pull request by kenkirito**
#175

### CODE REVIEW

**Comment by kenkirito** [comment]
@Jayshah6699 review this

**Comment by kenkirito** [comment]
@Jayshah6699 review my pr

**Comment by Jayshah6699** [comment]
name that folder used car prediction first.

**Comment by kenkirito** [comment]
@Jayshah6699 done

**Comment by Jayshah6699** [comment]
I am unable to see your uploaded ipynb file.

**Comment by kenkirito** [comment]
@Jayshah6699 let me know if there is a problem in my files I will make a new or

**Comment by Jayshah6699** [comment]
I am talking about the preview of ipynb file.

**Comment by kenkirito** [comment]
it is happing because file is to large

**Comment by kenkirito** [comment]
@Jayshah6699 i can share screenshot if you want

**Comment by Jayshah6699** [comment]
Mate I do not understand your predictions and not able to see the ipynb file...

**Comment by kenkirito** [comment]
you are not able to preview it because of its size should I share it on discord

**Comment by kenkirito** [comment]
@Jayshah6699 please refer to this for preview
https://github.com/kenkirito/carprediction

**Comment by Jayshah6699** [comment]
Can you decrease the notebook size?

**Comment by kenkirito** [comment]
i will try

**Comment by kenkirito** [comment]
@Jayshah6699 not able to reduce notebook size

**Comment by Jayshah6699** [comment]
Work on that a little bit and tell me what are the fields in the prediction(is it car's predicted price in the lakhs or something else)?

**Comment by kenkirito** [comment]
https://github.com/kenkirito/carprediction

**Comment by kenkirito** [comment]
data set is huge so getting this error and I have also used so many models for precision and increase my accuracy

**Pull request merged**
