### PR TITLE
TMDb Movie Analysis and Prediction

### PR DESCRIPTION
**Pull request by IndraP24**
# PR for #87 

* Removed the Previous Documented files
* Updated README.md (Added details of Implementation)

### CODE REVIEW

**Comment by Jayshah6699** [comment]
Just change the file name. It is still having the sem 3 name

**Comment by IndraP24** [comment]
@Jayshah6699 Oh yeah, Sorry will do that right now

**Comment by IndraP24** [comment]
@Jayshah6699 Done!

**Comment by Jayshah6699** [comment]
Just add the link of dataset in the readme file and I will merge it right away

**Comment by IndraP24** [comment]
@Jayshah6699 I've added the links to the Original dataset from Kaggle, the website that cataloged the Dataset, and the download link to the Unclean Dataset I used.

**Comment by IndraP24** [comment]
@Jayshah6699 Thanks!

**Pull request merged**
